language: php
php:
  - '7.2.19'
before_install:
  - travis_retry composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/psalm --show-info=false
  - vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)